
openapi: 3.0.3
info:
  title: User Service API
  version: 1.1.0
paths:
  /users:
    get:
      summary: Получить список пользователей
      responses:
        '200':
          description: Список пользователей
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

  /user:
    post:
      summary: Создать нового пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        '201':
          description: Пользователь создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /user/{id}:
    get:
      summary: Получить пользователя по ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Данные пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Не найден

    put:
      summary: Обновить данные пользователя
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
      responses:
        '200':
          description: Обновлено успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

    delete:
      summary: Удалить пользователя
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Удалено

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        фамилия:
          type: string
        имя:
          type: string
        отчество:
          type: string
        email:
          type: string
          format: email
        пароль:
          type: string
        аватар:
          type: string
          format: binary
        статус:
          type: string
          enum: [студент, преподаватель]

    UserCreate:
      type: object
      required: [фамилия, имя, email, пароль, статус]
      properties:
        фамилия:
          type: string
        имя:
          type: string
        отчество:
          type: string
        email:
          type: string
        пароль:
          type: string
        аватар:
          type: string
          format: binary
        статус:
          type: string
          enum: [студент, преподаватель]

    UserUpdate:
      type: object
      properties:
        фамилия:
          type: string
        имя:
          type: string
        отчество:
          type: string
        email:
          type: string
        пароль:
          type: string
        аватар:
          type: string
          format: binary
        статус:
          type: string
          enum: [студент, преподаватель]
