version: "3.8"

services:

  auth-service:
    build: ./auth_service
    container_name: auth-service
    expose:
      - "3005"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`api.riscvcourse.ru`) && PathPrefix(`/auth`)"
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.routers.auth.tls.certresolver=myresolver"
      - "traefik.http.middlewares.auth-stripprefix.stripprefix.prefixes=/auth"

      # CORS middleware
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=https://www.riscvcourse.ru,https://riscvcourse.ru,http://localhost:5173"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,POST,OPTIONS"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowcredentials=true"

      - "traefik.http.routers.auth.middlewares=auth-stripprefix,cors"
    env_file:
      - ./auth_service/.env
      
    depends_on:
      - keycloak

  postgres:
    image: postgres:15
    container_name: keycloak-db

    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak

    ports:
      - "5434:5432"
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak

      KC_BOOTSTRAP_ADMIN_USERNAME: pavel_mernov_admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: pavel_mernov_admin

      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: "true"
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.myresolver.acme.email=paulmernov@gmail.com
      - --certificatesresolvers.myresolver.acme.storage=/acme.json
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json:/acme.json
    restart: always

  compilation-service:
    build: ./compilation_service
    container_name: compilation-service
    labels:
      - "traefik.enable=true"

      # роутер
      - "traefik.http.routers.compilation.rule=Host(`api.riscvcourse.ru`) && PathPrefix(`/compilation`)"
      - "traefik.http.routers.compilation.entrypoints=websecure"
      - "traefik.http.routers.compilation.tls.certresolver=myresolver"

      # strip prefix
      - "traefik.http.middlewares.compilation-stripprefix.stripprefix.prefixes=/compilation"

      # CORS middleware
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=https://www.riscvcourse.ru,https://riscvcourse.ru,http://localhost:5173"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,POST,OPTIONS"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowcredentials=true"

      # подключаем оба middleware
      - "traefik.http.routers.compilation.middlewares=compilation-stripprefix,cors"

      - "traefik.http.services.compilation.loadbalancer.server.port=3000"


    expose:
      - "3000"
    environment:
      NODE_ENV: production
      SANDBOX_URL: http://rars-sandbox:3006
    
    volumes:
      - ./compilation_service/src/logs:/combined.logs
      - ./compilation_service/src/logs:/error.log

  rars-sandbox:
    build: ./rars_sandbox
    container_name: rars-sandbox
    ports:
      - "3006:3006"
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.5"

  mock-auth-service:
    build: ./mock_auth_service
    container_name: mock-auth-service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mockauth.rule=Host(`api.riscvcourse.ru`) && PathPrefix(`/mockauth`)"
      - "traefik.http.routers.mockauth.entrypoints=websecure"
      - "traefik.http.routers.mockauth.tls.certresolver=myresolver"
      - "traefik.http.middlewares.mockauth-stripprefix.stripprefix.prefixes=/mockauth"

      # CORS middleware
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=https://www.riscvcourse.ru,https://riscvcourse.ru,http://localhost:5173"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,POST,OPTIONS"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowcredentials=true"

      - "traefik.http.routers.mockauth.middlewares=mockauth-stripprefix,cors"
    expose:
      - "3003"
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
    volumes:
      - ./mock_auth_service/src/logs:/combined.logs
      - ./mock_auth_service/src/logs:/error.log

  contest-service:
    build: ./contest_service
    container_name: contest-service
    depends_on:
      - contest-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.contest.rule=Host(`api.riscvcourse.ru`) && PathPrefix(`/contest`)"
      - "traefik.http.routers.contest.entrypoints=websecure"
      - "traefik.http.routers.contest.tls.certresolver=myresolver"
      - "traefik.http.middlewares.contest-stripprefix.stripprefix.prefixes=/contest"

      # CORS middleware
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=https://www.riscvcourse.ru,https://riscvcourse.ru,http://localhost:5173"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowcredentials=true"

      - "traefik.http.routers.contest.middlewares=contest-stripprefix,cors"
    expose:
      - "3002"
    environment:
      NODE_ENV: production
    volumes:
      - ./contest_service/src/logs:/combined.logs
      - ./contest_service/src/logs:/error.log

  submission-service:
    build: ./submission_service
    container_name: submission-service
    depends_on:
      - submission-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.submission.rule=Host(`api.riscvcourse.ru`) && PathPrefix(`/submission`)"
      - "traefik.http.routers.submission.entrypoints=websecure"
      - "traefik.http.routers.submission.tls.certresolver=myresolver"
      - "traefik.http.middlewares.submission-stripprefix.stripprefix.prefixes=/submission"
      - "traefik.http.routers.submission.middlewares=submission-stripprefix"
    expose:
      - "3004"
    environment:
      NODE_ENV: production
    volumes:
      - ./submission_service/src/logs:/combined.logs
      - ./submission_service/src/logs:/error.log

  contest-db:
    image: postgres:18
    container_name: contest-db
    environment:
      POSTGRES_USER: pavel_mernov
      POSTGRES_PASSWORD: 0867
      POSTGRES_DB: contest_database
    volumes:
      - contest_volumes:/var/lib/postgresql

  submission-db:
    image: postgres:18
    container_name: submission-db
    environment:
      POSTGRES_USER: pavel_mernov
      POSTGRES_PASSWORD: 0867
      POSTGRES_DB: submission_database
    volumes:
      - submission_volumes:/var/lib/postgresql

  redis:
    image: redis
    container_name: redis

volumes:
  submission_volumes:
  contest_volumes:
  keycloak_db_data:

networks:
  default:
    driver: bridge