openapi: 3.0.3
info:
  title: RISCV Course Platform API
  version: 1.0.0
  description: |
    Центральный swagger-файл, объединяющий все сервисы:
    - Auth Service
    - User Service
    - Course Service
    - Submission Service
servers:
  - url: http://localhost:8000
    description: API Gateway
paths: {}
components:
  schemas: {}
tags:
  - name: Auth Service
  - name: User Service
  - name: Course Service
  - name: Submission Service
externalDocs:
  description: Подробные спецификации сервисов
  url: ./Auth Service/swagger.yaml
  url: ./Course Service/swagger.yaml
  url: ./User Service/swagger.yaml
  url: ./Submission Service/swagger.yaml
