openapi: 3.0.3
info:
  title: RISCV Course Platform API
  version: 1.0.0
  description: |
    Центральный swagger-файл, объединяющий все сервисы:
    - Auth Service
    - Compilation Service    
    - Contest Service
    - Submission Service
servers:
  - url: http://localhost:8000
    description: API Gateway
paths: {}
components:
  schemas: {}
tags:
  - name: Auth Service
  - name: Course Service
  - name: Submission Service
externalDocs:
  description: Подробные спецификации сервисов
  url: ./AuthService/swagger.yaml
  url: ./ContestService/swagger.yaml
  url: ./CompilationService/swagger.yaml
  url: ./SubmissionService/swagger.yaml
