http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

    default-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        sslRedirect: true
        accessControlAllowOrigin: "*"
        accessControlAllowMethods: "GET,OPTIONS,PUT,POST,DELETE"
        accessControlAllowHeaders: "Content-Type,Authorization"

  routers:
    http-to-https:
      rule: "HostRegexp(`{host:.+}`)"
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      service: noop@internal

    acme-http-challenge:
      rule: "PathPrefix(`/.well-known/acme-challenge/`)"
      entryPoints:
        - web
      service: noop@internal

  services:
    noop:
      loadBalancer:
        servers:
          - url: "130.49.150.32"